/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "report-pink": "#ff2067",
        "surface-tint": "#5f5e5e",
        "on-secondary": "#ffffff",
        "ink-subtle": "#7b7b78",
        "brand-blue": "#0007cb",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed-variant": "#822800",
        "on-surface": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444748",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#868381",
        "outline": "#747878",
        "hairline": "#d3cec6",
        "surface-1": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "on-secondary-container": "#fffbff",
        "surface-container-low": "#f7f3f2",
        "tertiary-container": "#1d1b1a",
        "on-tertiary-fixed-variant": "#484645",
        "fin-orange": "#ff5600",
        "background": "#fdf8f8",
        "on-background": "#1c1b1b",
        "report-green": "#0bdf50",
        "secondary-fixed": "#ffdbcf",
        "on-primary-fixed-variant": "#474646",
        "ink-muted": "#626260",
        "surface-container": "#f1edec",
        "error": "#ba1a1a",
        "secondary-container": "#d04500",
        "on-primary-fixed": "#1c1b1b",
        "primary": "#000000",
        "canvas": "#f5f1ec",
        "on-secondary-fixed": "#380c00",
        "tertiary-fixed": "#e6e1df",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#cac6c3",
        "on-tertiary-fixed": "#1d1b1a",
        "on-primary-container": "#858383",
        "primary-container": "#1c1b1b",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#ffb59c",
        "on-error-container": "#93000a",
        "surface-dim": "#ddd9d8",
        "inverse-on-surface": "#f4f0ef",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c8c6c5",
        "tertiary": "#000000",
        "on-error": "#ffffff",
        "surface-2": "#ebe7e1",
        "surface-variant": "#e5e2e1",
        "surface": "#fdf8f8",
        "secondary": "#a63500",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#fdf8f8",
        "surface-container-high": "#ebe7e6",
        "report-blue": "#65b5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xxs": "4px",
        "xs": "8px",
        "sm": "12px",
        "md": "16px",
        "xxl": "48px",
        "lg": "24px",
        "xl": "32px",
        "section": "96px"
      },
      fontFamily: {
        "eyebrow": ["Saans", "sans-serif"],
        "body-lg": ["Saans", "sans-serif"],
        "headline": ["Saans", "sans-serif"],
        "display-xl": ["Saans", "sans-serif"],
        "subhead": ["Saans", "sans-serif"],
        "display-lg": ["Saans", "sans-serif"],
        "button": ["Saans", "sans-serif"],
        "card-title": ["Saans", "sans-serif"],
        "display-md": ["Saans", "sans-serif"],
        "mono": ["SaansMono", "monospace"],
        "caption": ["Saans", "sans-serif"],
        "body-sm": ["Saans", "sans-serif"],
        "body": ["Saans", "sans-serif"]
      },
      fontSize: {
        "eyebrow": ["14px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.5", "letterSpacing": "-0.1px", "fontWeight": "400" }],
        "headline": ["28px", { "lineHeight": "1.2", "letterSpacing": "-0.5px", "fontWeight": "500" }],
        "display-xl": ["72px", { "lineHeight": "1.05", "letterSpacing": "-2.0px", "fontWeight": "500" }],
        "subhead": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.2px", "fontWeight": "400" }],
        "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-1.4px", "fontWeight": "500" }],
        "button": ["15px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "card-title": ["22px", { "lineHeight": "1.25", "letterSpacing": "-0.3px", "fontWeight": "500" }],
        "display-md": ["40px", { "lineHeight": "1.15", "letterSpacing": "-0.8px", "fontWeight": "500" }],
        "mono": ["13px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
};

